### ISSUE TITLE
Help with Docker

### ISSUE THREAD

**Issue by tidusjar** [rogueosb/docker-ombi#1]
Hi Rogueosb!

Are you able to assist with this: https://github.com/tidusjar/PlexRequests.Net/issues/165 ?

**Comment by rogueosb** [comment]
I've created a new image that appears to work under my initial testing: [https://github.com/rogueosb/docker-plexrequestsnet-alpine](https://github.com/rogueosb/docker-plexrequestsnet-alpine)

**Comment by tidusjar** [comment]
Thanks! You are awesome!
