### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by tidusjar** [rogueosb/docker-ombi#10]
Hi,

I noticed you already changed the name! Nice!

One thing that you may have missed is that the .zip file name has also changed to `ombi.zip` rather than `plexrequests.zip`

I have also changed the DB name.

If the file `plexrequests.sqlite` exists then I will use that, otherwise I'll create a new file called `ombi.sqlite`

**Comment by rogueosb** [comment]
Thanks for the heads up, I'll get those changed.

**Comment by tidusjar** [comment]
No problem :)

**Comment by luxus** [comment]
and you should update your read me
the other thing is the repository in the docker hub has the "wrong" name as well :D

**Comment by rogueosb** [comment]
Unfortunately docker won't let me rename an existing repo, but I will probably just spin up a new one with the new name once a new stable release is out with the DB name changes (while leaving the old one linked to this repo).

**Comment by brianbuquoi** [comment]
The README needs to be updated to point to rogueosb/ombi instead of rogueosb/plexrequestsnet on the Usage section.

**Comment by rogueosb** [comment]
Migration to new name should be complete now.
