### ISSUE TITLE
Access to EAP version?

### ISSUE THREAD

**Issue by 1activegeek** [rogueosb/docker-ombi#12]
I see there is a command to be able to install the DEV branch of the app. Any plans or would it be easy enough to add in an environment flag to enable the Early Access Preview branch?

**Comment by rogueosb** [comment]
Unless there's a compiled release of it available for download, unfortunately not. The EAP branch seems to be mostly in sync with the dev branch at the minute anyway, from what I can tell.

**Comment by 1activegeek** [comment]
Ahhh ok. I wasn't sure. I dug into the files a bit and it did look like you were pulling from a specific location which I'm not aware if they make a compiled version available. Guess I'll play around with the DEV branch and see how stable it is if it's close to the EAP branch. I can afford issues, just don't want something totally unstable and unusable.
