### ISSUE TITLE
Database owner

### ISSUE THREAD

**Issue by ghost** [rogueosb/docker-ombi#13]
Ombi currently creates it's database and Backup folder under the username and group nobody:nogroup.
It would be great if we could change the user and group with the -e PUID=1000 and -e PGID=1000 flags.

**Comment by rogueosb** [comment]
Added support for those environment labels, give them a try and let me know if there's any issues. It should set the ownership of the existing config files to the new user and group you set.

**Comment by ghost** [comment]
Works great! Thank you.
