### ISSUE TITLE
Add flag to set baseurl

### ISSUE THREAD

**Issue by onedr0p** [rogueosb/docker-ombi#14]
One of the startup options for ombi allows you to set the `-base` flag with a path following it like `/ombi` to allow for easy reverse proxy on the host

**Comment by rogueosb** [comment]
Does using the RUN_OPTS flag not work for this already? I haven't tested it myself.

**Comment by onedr0p** [comment]
oh, I didn't know how that worked. I'll give it a try.

**Comment by onedr0p** [comment]
n/m it worked :)
