### ISSUE TITLE
Updating reboots but no update

### ISSUE THREAD

**Issue by henkjanvries** [rogueosb/docker-ombi#18]
When ever i try to update within the app, in a docker on my synology, it seems like its doing something, even the terminal output shows that ombi.zip gets downloaded, but eventually it turns back to the same version.

**Comment by rogueosb** [comment]
I had that bug on 2.0 but I think it was fixed in the next version. Try restarting the container, that should download the latest update, or if that fails to work, update the image. Let me know how it goes.
