### ISSUE TITLE
Any chance of a new build

### ISSUE THREAD

**Issue by simonk83** [rogueosb/docker-ombi#19]
Sorry to create an issue, couldn't work out how to contact you directly.  I'm keen to try the Emby functionality but it's only in the latest EAP/DEV builds.  Could you pull down the latest build for the docker? 

Thanks!

**Comment by rogueosb** [comment]
Have you tried adding `-e EAP=1` to your run command?

**Comment by simonk83** [comment]
I run Docker on a synology, but I've added that variable:

<img width="621" alt="untitled" src="https://cloud.githubusercontent.com/assets/518440/22868793/e314a86a-f1ed-11e6-9c4b-2d136862a258.png">


I must be doing something wrong :)

**Comment by rogueosb** [comment]
That's very strange, it's working fine on my end running on Ubuntu. Unfortunately I don't have a synology to test on, but if you're sure you're running the latest rogueosb/ombi image (the old plexrequests one doesn't work anymore) some logs might help me identify the issue.

**Comment by simonk83** [comment]
No worries, just heading out for an hour or so but I'll get you some a
little later. I've pulled the latest image, but after enabling that EAP
flag should it download the latest version on startup?

**Comment by simonk83** [comment]
So it just needs a /config folder setup right?   I see in the logs it's inflating files from the zip, but my config folder just contains the sqlite db and a backup folder

**Comment by simonk83** [comment]
Ok:

<img width="553" alt="ombivol" src="https://cloud.githubusercontent.com/assets/518440/22871387/8df82ade-f204-11e6-9ea6-0da0f274c8f1.png">
<img width="1025" alt="ombipath" src="https://cloud.githubusercontent.com/assets/518440/22871390/90465702-f204-11e6-8d6d-842c734c6186.png">
<img width="587" alt="ombilog1" src="https://cloud.githubusercontent.com/assets/518440/22871392/941fd6d2-f204-11e6-9d69-ecb596934acd.png">

Bunch more unpacking in the middle here, then:

<img width="849" alt="ombilog2" src="https://cloud.githubusercontent.com/assets/518440/22871397/9fabc01a-f204-11e6-82a7-1d5cdbf0c355.png">

Where are the actual ombi files stored if not in /config?


Regardless, it looks like it's grabbing 2.1.1410, but not sure why I can't see the Emby stuff in the Wizard.   Is there a way to see what version it's actually running from the CLI?

**Comment by rogueosb** [comment]
It only uses the config folder to store your database and backups, and downloads the a fresh copy of ombi to the /app folder on every startup (using environment variable to decide which one. From the logs I can see it's definitely pulling one of the dev versions, however. Have you tried going to the Status page in the admin settings and changing the branch version from there? It's autoupdater might be fix the issue.

**Comment by simonk83** [comment]
My main issue is that I don't actually use Plex so I don't have it installed.  The EAP version is supposed to give an option in the wizard to use Emby instead.   I'd rather not have to install a version of Plex just to get through the wizard :D 

Worst case I'll just wait for it to hit the stable branch.  Thanks for your help though :)

**Comment by rogueosb** [comment]
Ah, I didn't realize you need Plex to get through the wizard! I can see Emby on my admin page, but it sounds like they haven't added it to the wizard yet.

**Comment by simonk83** [comment]
Hmm, I posted in the thread today and they mentioned it should be in the wizard, but I bet you're right.  All good, maybe I'll just instead Plex in a docker and trash it afterwards (the beauty of docker!)

Thanks again

**Comment by tobsen987** [comment]
I know this one is closed for a while now, but I ran in the same problem on my synology.
Even tough EAP=1 was set, it always fetched the dev version. Had to set DEV=0 and EAP=1, then it works.
