### ISSUE TITLE
[Request] Use dev branch

### ISSUE THREAD

**Issue by bjonness406** [rogueosb/docker-ombi#2]
Would it be possible to add an option to use the dev branch of plexrequestsnet?
Either with an Environment Variable (dev and master), or with a different tag on the docker image on dockerhub.

**Comment by rogueosb** [comment]
Currently the stable branch is compiled by the dev and uploaded as a release. As far as I can tell, this is not done with the dev branch. Unless you would want the container to compile the dev branch every time it is run, I'm not sure how you would go about doing this.

**Comment by bjonness406** [comment]
I see, no problem then. 
Thanks for the help, and the docker image :)

**Comment by jrdnlc** [comment]
How about being able to set the variable to master or dev? I don't know much about docker but I see a few docker apps that have the option under advanced settings in unraid.

**Comment by jrdnlc** [comment]
Being able to switch to dev would allow me to test the dev builds since i'm a tester.

**Comment by rogueosb** [comment]
Most docker containers that have that environment variable usually run a program that can be run directly from source rather than having to be pre-compiled. Unless there's a source for precompiled dev releases it won't be easy to implement this.

**Comment by tidusjar** [comment]
Only just seen this. The dev builds are compiled on every checkin, just not uploaded to Github.
You can find all of the compiled builds here: https://ci.appveyor.com/project/tidusjar/requestplex

**Comment by bjonness406** [comment]
Ohh, Nice.

Is there a standard link we can use, that always have the latest build? Like it is on github ( https://api.github.com/repos/tidusjar/PlexRequests.Net/releases/latest ).

rogueosb, is this something you could do then? Add another branch with a different download link.

**Comment by rogueosb** [comment]
I'll have a look later this week to see if I can implement this.

**Comment by tidusjar** [comment]
I'm not sure if there is a way to get the latest. The thing to watch out for is you only really want the builds from the dev branch.

But please beware, sometimes there are things checked into the dev branch that are not fully complete. Like currently I have some unfinished functionality and there will be bugs with any new features

**Comment by rogueosb** [comment]
I've added an environment label that downloads the latest successful build from the dev branch on Appveyor. I tested it briefly to check that it selects the right branch, but nothing further than that. And as Jamie said, use at your own risk!

**Comment by tidusjar** [comment]
Yeah, thanks. :+1:

**Comment by bjonness406** [comment]
@rogueosb 

Thank you very much, appreciate it!
