### ISSUE TITLE
email via gmail not sent

### ISSUE THREAD

**Issue by henkjanvries** [rogueosb/docker-ombi#20]
Hi!

Ive got ombi setup on my synology in a docker.
When i setup the email notification i go through the setup with gmail:
<img width="388" alt="schermafbeelding 2017-02-13 om 6 06 24 pm" src="https://cloud.githubusercontent.com/assets/737006/22893820/2a2cb99e-f217-11e6-9c19-9fb7e34f117d.png">
And because of the 2step authentication i have, ive added the app password generated by google. all seems to work as the test gets verified correctly.

But i cant seem to get any test emails in the admin account.
correct email adres has been added on all fronts but nothing seems to actually send the email.

**Comment by rogueosb** [comment]
This is probably a question better answered by the Ombi devs, this is just the docker container!

[https://github.com/tidusjar/Ombi](https://github.com/tidusjar/Ombi)
