### ISSUE TITLE
Ombi not seeing plex

### ISSUE THREAD

**Issue by henkjanvries** [rogueosb/docker-ombi#21]
It can search and find, but eventually it wont index my plex.
it will keep giving this notification:
Currently we are indexing all of the available tv shows and movies on the media server, so there might be some unexpected behavior. This shouldn't take too long.

But when reconnecting in ombi, it will just give a good response notification that plex is connected. It even gets the token..

**Comment by rogueosb** [comment]
This is probably best answered by the Ombi devs: [https://github.com/tidusjar/Ombi](https://github.com/tidusjar/Ombi)
