### ISSUE TITLE
Config Parameter?

### ISSUE THREAD

**Issue by ryanmcgr** [rogueosb/docker-ombi#23]
Hi,
Brand new to the docker thing and trying to struggle my way through installing some packages, including Ombi. Not sure what I should be passing in the "-v /**your-config-location**:/config" parameter .. Apologies for the ultra-newb question, but I wasn't finding much on my own.

Thanks,
Ryan

**Comment by rogueosb** [comment]
Set that to the path on your host where you want the /config path in the guest container to map to. E.g. /opt/ombi . Reading the docker documentation might be useful to know what each run parameter does! :)

**Comment by ryanmcgr** [comment]
Thanks for the quick response. And yes, I've been fumbling my way through the documentation, just wasn't clear if the config location was supposed to be on the host side. So if I'm running docker on Windows, that would be "C:\Ombi" or wherever I'm putting it I suppose, yea?

Thanks!
Ryan

**Comment by rogueosb** [comment]
Yes that's correct. I'm not entirely sure on Windows if the syntax is the same, but if it doesn't work I'm sure there's plenty of info out there.

**Comment by ryanmcgr** [comment]
Great, thanks again!
