### ISSUE TITLE
Recently have an issue starting the container

### ISSUE THREAD

**Issue by slbailey** [rogueosb/docker-ombi#27]
Getting Stable Version ()
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
Unzipping...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chmod: cannot access '/app/Ombi/Ombi': No such file or directory
s6-applyuidgid: fatal: unable to exec /app/Ombi/Ombi: No such file or directory
/start.sh exited 111

**Comment by rogueosb** [comment]
Hello, sorry you are having issues! Unfortunately, I will not be updating this image any longer, but instead I'd recommend you have a look at an actively maintained one, e.g. here: https://hub.docker.com/r/linuxserver/ombi. I'll be sure to update the repo with a deprecation notice to let others know.
