### ISSUE TITLE
1.8.4 Naming convention

### ISSUE THREAD

**Issue by brianbuquoi** [rogueosb/docker-ombi#3]
It looks like because 1.8.4 was named PlexRequests.1.zip, while the old ones were called PlexRequests.zip, the docker freaks out and is unable to run the newest update and continuously restarts itself over and over.

I've stopped using this docker until the next release when this can hopefully be resolved.

**Comment by rogueosb** [comment]
I've updated the image, and on my end it seems to be working OK. Could you test it and see if it fixes the issue on your end as well?

**Comment by brianbuquoi** [comment]
It resolved the issue. Thanks! :)
