### ISSUE TITLE
Container fails to start - Unneeded name change?

### ISSUE THREAD

**Issue by SoftNotWork** [rogueosb/docker-ombi#9]
The name change or something else has caused the containers to fail to start. I can blow it away, start a new container, and it still will not start.

Status:

Restarting (2) 3 seconds ago

That is all I've got. Docker is usually very easy until something like this breaks with no explanation.

Thank you in advance for any help getting this resolved.

**Comment by rogueosb** [comment]
Are you using the latest image from Docker Hub? There were some recent changes that should be fixed in that version (I've just tested it on a fresh VM on my end).

**Comment by SoftNotWork** [comment]
I can confirm that it fails to start with this command. It hasn't been fixed. The software stopped working when the name changed and hasn't worked since.

docker run -d -i --name ombi --restart=always -p "3579:3579" -v /opt/plexreqnet:/config rogueosb/plexrequestsnet

The Docker VM never starts and endlessly restarts. No fixes have been found. It simply restarts endlessly in a loop.

STATUS

Restarting (2) 28 seconds ago

docker -v
Docker version 1.10.3, build 3999ccb-unsupported

**Comment by rogueosb** [comment]
Would you be able to post the container logs (docker logs ombi)? My hunch is that it's failing to download the latest release, so it crashes when trying to run.

**Comment by Electronickss** [comment]
Not the original person who opened this but I'm having the same issue. I have attached my logs here

[dockerLogsOmbi.txt](https://github.com/rogueosb/docker-ombi/files/674648/dockerLogsOmbi.txt)

`docker -v`
`Docker version 1.12.5, build 7392c3b`

**Comment by rogueosb** [comment]
I've merged my test branch, reverting back to API downloads, and getting ready for the transition to non-beta Ombi. If you could try again with the new docker hub image (rogueosb/ombi) and report back, that would be great. You can use the exact same command, simply replace the image to use.

**Comment by Electronickss** [comment]
> image to use

And if I'm not pinning on a version it should just pull the latest correct?

**Comment by rogueosb** [comment]
You might need to force pull the latest version using (at least I do using docker-compose):
docker pull rogueosb/ombi

**Comment by Electronickss** [comment]
Ill try this out later today

**Comment by Electronickss** [comment]
Sorry I'm a bit late on this.

I ended up adding `docker images |grep -v REPOSITORY|awk '{print $1}'|xargs -L1 docker pull` as a cron job so I don't have any more stale images on my host. It's updating now and I will let you know when i pull the newest version, and give you my logs

**Comment by Electronickss** [comment]
And its good to go!
